name: FloatingTexter
author: Fycarman
version: G 1.2
main: FloatingTexter\Main
api: [3.0.0-ALPHA9]
description: "A simple plugin to spawn FloatingTexts around the worlds. Thanks to @TheNewHEROBRINEX and @luca28pet for helping me with some problems."
commands:
   floatingtext:
       aliases: [ft, floatingtexter]
       description: "FloatingTexter's main command"
permission:
   floatingtexter.use:
       default: op
       description: "Allow to use /ft command"
